version: "3"
services:
  pywishlist:
    container_name: goinghome
    restart: unless-stopped
    image: ghcr.io/oxivanisher/pygoinghome:master
    # build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config:ro
